const SHEET_ID='1DTr0mw4bfpTSMrHtQYNIUUV4-XjsedSTmqNlZZWmIvE';
const SOURCES={protestante:{gid:'1844484584',label:'Protestante'},catolica:{gid:'789433062',label:'Católica'}};
const PAGE_SIZE=50;
let headers=[],data=[],filtered=[],page=1;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows;}
function toObjects(rows){if(!rows.length)return[];headers=rows[0].map(h=>h.trim());return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
function value(o,k){return o[k]??''}
function setSource(state,msg){const ok=state==='ok',loading=state==='loading';$('sourceStatus').textContent=loading?'Cargando Banco Maestro…':ok?'Datos cargados':'Fuente no publicada';$('sourceDetail').textContent=msg;document.querySelector('.dot').style.background=ok?'var(--green)':loading?'var(--cyan)':'var(--amber)';}
async function fetchCsv(url){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);const text=await res.text();if(/<!doctype html|<html/i.test(text))throw new Error('Respuesta HTML');const rows=parseCSV(text);if(!rows.length||!rows[0].includes('ID'))throw new Error('CSV no válido');return text;}
async function loadLive(){const src=SOURCES[$('tradition').value];setSource('loading',`Intentando cargar la pestaña ${src.label}…`);$('loadLive').disabled=true;try{const urls=[`https://docs.google.com/spreadsheets/d/${SHEET_ID}/pub?gid=${src.gid}&single=true&output=csv`,`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&gid=${src.gid}`];let text=null,lastError=null;for(const url of urls){try{text=await fetchCsv(url);break;}catch(e){lastError=e;}}if(!text)throw lastError||new Error('Sin fuente');loadData(toObjects(parseCSV(text)));setSource('ok',`${src.label}: ${data.length.toLocaleString('es-PE')} registros cargados automáticamente.`);}catch(e){setSource('error','Para la carga automática, publica únicamente Banco_protestante y Banco_catolico en Google Sheets. Mientras tanto puedes usar “Cargar CSV”.');renderEmpty('La página está lista, pero las pestañas del banco todavía no están publicadas para lectura web.');}finally{$('loadLive').disabled=false;}}
function loadData(rows){data=rows;page=1;populateFilters();applyFilters();updateStats();}
function unique(k){return [...new Set(data.map(o=>value(o,k)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));}
function fillSelect(id,k){const s=$(id),current=s.value;s.innerHTML='<option value="">Todos</option>'+unique(k).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if([...s.options].some(o=>o.value===current))s.value=current;}
function populateFilters(){fillSelect('testament','Testamento');fillSelect('book','Libro');fillSelect('level','Nivel');fillSelect('qa','Estado_QA');fillSelect('human','Revision_humana');}
function applyFilters(){const term=$('search').value.trim().toLowerCase();const rules=[['testament','Testamento'],['book','Libro'],['level','Nivel'],['qa','Estado_QA'],['human','Revision_humana']];filtered=data.filter(o=>{if(term&&!Object.values(o).join(' ').toLowerCase().includes(term))return false;return rules.every(([id,k])=>!$(id).value||value(o,k)===$(id).value);});const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));if(page>pages)page=pages;render();}
function badge(v){const t=String(v||'—');let cls='';if(/si|verificado|publicable|revisado|apto/i.test(t))cls='ok';else if(/revisar|no|pendiente/i.test(t))cls='warn';return `<span class="badge ${cls}">${esc(t)}</span>`;}
function render(){const start=(page-1)*PAGE_SIZE,slice=filtered.slice(start,start+PAGE_SIZE);$('visibleCount').textContent=filtered.length.toLocaleString('es-PE');$('rows').innerHTML=slice.length?slice.map((o,i)=>`<tr><td><strong>${esc(value(o,'ID'))}</strong></td><td>${esc(value(o,'Referencia'))}</td><td>${esc(value(o,'Libro'))}</td><td>${badge(value(o,'Nivel'))}</td><td class="question-cell">${esc(value(o,'Pregunta'))}</td><td>${esc(value(o,'Respuesta_correcta'))}</td><td>${badge(value(o,'Estado_QA'))}</td><td>${badge(value(o,'Revision_humana'))}</td><td><button class="row-button" data-index="${start+i}">Ver detalle</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty">No hay preguntas que coincidan con los filtros.</td></tr>';$('pageInfo').textContent=`Página ${page} de ${Math.max(1,Math.ceil(filtered.length/PAGE_SIZE))}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=Math.ceil(filtered.length/PAGE_SIZE);document.querySelectorAll('.row-button').forEach(b=>b.addEventListener('click',()=>openDetail(filtered[Number(b.dataset.index)])));}
function renderEmpty(msg){data=[];filtered=[];$('rows').innerHTML=`<tr><td colspan="9" class="empty">${esc(msg)}</td></tr>`;$('visibleCount').textContent='0';updateStats();}
function updateStats(){const count=(k,v)=>data.filter(o=>value(o,k).toLowerCase()===v.toLowerCase()).length;$('statTotal').textContent=data.length.toLocaleString('es-PE');$('statReview').textContent=count('Estado_QA','Revisar').toLocaleString('es-PE');$('statHuman').textContent=count('Revision_humana','Si').toLocaleString('es-PE');$('statVerified').textContent=count('Estado_QA','Verificado').toLocaleString('es-PE');$('statPublishable').textContent=count('Estado_QA','Publicable').toLocaleString('es-PE');$('statActive').textContent=count('Activa_app','Si').toLocaleString('es-PE');}
function openDetail(o){if(!o)return;$('detailTitle').textContent=`${value(o,'ID')} · ${value(o,'Referencia')}`;const priority=new Set(['Pregunta','Opcion_A','Opcion_B','Opcion_C','Opcion_D','Respuesta_correcta','Explicacion_breve','Observaciones']);$('detailBody').innerHTML=headers.filter(h=>value(o,h)!=='').map(h=>`<dl class="detail-item ${priority.has(h)?'wide':''}"><dt>${esc(h.replaceAll('_',' '))}</dt><dd>${esc(value(o,h))}</dd></dl>`).join('');$('detailDialog').showModal();}
$('loadLive').addEventListener('click',loadLive);
$('tradition').addEventListener('change',()=>{renderEmpty('Cargando la tradición seleccionada…');loadLive();});
$('csvFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();loadData(toObjects(parseCSV(text)));setSource('ok',`CSV local: ${f.name} · ${data.length.toLocaleString('es-PE')} registros.`);e.target.value='';});
['search','testament','book','level','qa','human'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{page=1;applyFilters();}));
$('clearFilters').addEventListener('click',()=>{$('search').value='';['testament','book','level','qa','human'].forEach(id=>$(id).value='');page=1;applyFilters();});
$('prevPage').addEventListener('click',()=>{if(page>1){page--;render();}});$('nextPage').addEventListener('click',()=>{if(page*PAGE_SIZE<filtered.length){page++;render();}});$('closeDialog').addEventListener('click',()=>$('detailDialog').close());$('detailDialog').addEventListener('click',e=>{if(e.target===$('detailDialog'))$('detailDialog').close();});
window.addEventListener('DOMContentLoaded',loadLive);